apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-chat
  namespace: go-chat
  labels:
    app: go-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-chat
  template:
    metadata:
      labels:
        app: go-chat
    spec:
      containers:
      - name: go-chat
        image: ghcr.io/haahaakon/go-chat:latest
        ports:
        - containerPort: 9988
          name: tcp
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-chat
  namespace: go-chat
  labels:
    app: go-chat
  annotations:
    metallb.io/ip-allocated-from-pool: ipv6-default
spec:
  type: LoadBalancer
  ports:
  - port: 9988
    targetPort: 9988
    protocol: TCP
    name: tcp
  selector:
    app: go-chat
